# dloom configuration file
version: 0.0.1

# Global configuration
sourceDir: "/home/username/dotfiles"        # Base directory for dotfiles
targetDir: "/home/username"                 # Where symlinks will be created
backupDir: "/home/username/.dloom/backups"  # Where existing files are backed up
force: false                                # Don't replace files without asking
verbose: true                               # Show detailed output
dryRun: false                               # Actually make changes

# Package-specific configurations
packages:
  # Vim configuration
  vim:
    targetDir: "/home/username/.config/vim"  # Override target for this package
    conditions:                              # Only link if these conditions are met
      os:                                    # OS conditions (OR logic within this group)
        - "linux"
        - "darwin"
      executable:                    # Required executables (AND logic with other groups)
        - "vim"
    files:                           # File-specific configurations
      "vimrc":                       # Exact file match
        targetDir: "/home/username"  # Override target directory for this file
      "regex:^colors/.*\\.vim$":     # Regex pattern for matching files
        conditions:                  # File-specific conditions
          os:
            - "linux"                # Only link color schemes on Linux
      "plugins/nerdtree.vim":        # Specific file path
        conditions:
          executable:                # Only link if NERDTree plugin requirements are met
            - "git"

  # Neovim configuration
  nvim:
    targetDir: "/home/username/.config/nvim"
    conditions:
      executable:
        - "nvim"
    files:
      "init.vim":
        force: true                  # Always overwrite init.vim without asking

  # Shell configurations
  shell:
    files:
      "bashrc":
        targetDir: "/home/username"  # Will create ~/.bashrc
        conditions:
          executable:
            - "bash"
      "zshrc":
        targetDir: "/home/username"  # Will create ~/.zshrc
        conditions:
          executable:
            - "zsh"
      "common_aliases":              # Shared between shells
        targetDir: "/home/username"  # Will create ~/.common_aliases

  # Git configuration with OS-specific settings
  git:
    files:
      "gitconfig.common":            # Common git config
        targetDir: "/home/username"
        force: true
      "gitconfig.linux":
        targetDir: "/home/username"
        conditions:
          os:
            - "linux"
      "gitconfig.darwin":
        targetDir: "/home/username"
        conditions:
          os:
            - "darwin"

  # Terminal multiplexer with version-specific configs
  tmux:
    conditions:
      executable:
        - "tmux"
    files:
      "tmux.conf.new":
        targetDir: "/home/username"
        conditions:
          executable_version:
            "tmux": ">=3.0"
      "tmux.conf.legacy":
        targetDir: "/home/username"
        conditions:
          executable_version:
            "tmux": "<3.0"

  # Development tools
  dev:
    conditions:                      # Package-level conditions
      os:
        - "linux"
        - "darwin"
    files:
      "regex:^\\.?eslintrc(\\.json)?$":  # Match .eslintrc or eslintrc.json
        conditions:
          executable:
            - "node"
            - "npm"
          executable_version:
            "node": ">=12.0.0"
      "regex:^\\.?prettierrc(\\.json)?$":
        conditions:
          executable:
            - "node"
            - "npm"
      ".editorconfig":               # Editor configuration
        targetDir: "/home/username"  # Goes in home directory
        force: true                  # Always overwrite

  # Linux-specific configurations
  linux:
    conditions:
      os:
        - "linux"
    files:
      "i3/config":                   # i3 window manager config
        targetDir: "/home/username/.config/i3"
        conditions:
          executable:
            - "i3"
      "regex:^polybar/.*":           # All polybar configs
        targetDir: "/home/username/.config/polybar"
        conditions:
          executable:
            - "polybar"
      "picom.conf":
        targetDir: "/home/username/.config"
        conditions:
          executable:
            - "picom"

  # macOS-specific configurations
  macos:
    conditions:
      os:
        - "darwin"
    files:
      "DefaultKeyBinding.dict":
        targetDir: "/home/username/Library/KeyBindings"
      "regex:^karabiner/.*":
        targetDir: "/home/username/.config/karabiner"
        conditions:
          executable:
            - "karabiner_cli"

  # Distribution-specific configurations
  arch:
    conditions:
      distro:
        - "arch"
    files:
      "pacman.conf":
        targetDir: "/etc"
        backupDir: "/home/username/.dloom/backups/etc"
        conditions:
          # Only link if user has sudo access to modify system files
          executable:
            - "sudo"

  ubuntu:
    conditions:
      distro:
        - "ubuntu"
        - "debian"
    files:
      "apt/preferences":
        targetDir: "/etc/apt"
        backupDir: "/home/username/.dloom/backups/etc/apt"
        conditions:
          executable:
            - "sudo"
            - "apt"
