# dloom configuration file
version: 0.0.1 # Version of the configuration file

# Global configuration
source_dir: "/home/username/dotfiles"        # Base directory for dotfiles
target_dir: "/home/username"                 # Where symlinks will be created
backup_dir: "/home/username/.dloom/backups"  # Where existing files are backed up
force: false                                # Don't replace files without asking
verbose: true                               # Show detailed output
dry_run: false                               # Actually make changes

# Package-specific override configurations
link_overrides:
  # Vim configuration
  vim:
    target_dir: "/home/username/.config/vim"  # Override target for this package
    conditions:                              # Only link if these conditions are met
      os:                                    # OS conditions (OR logic within this group)
        - "linux"
        - "darwin"
      executable:                    # Required executables (AND logic with other groups)
        - "vim"
    file_overrides:                           # File-specific configurations
      "vimrc":                       # Exact file match
        target_dir: "/home/username"  # Override target directory for this file
      "regex:^colors/.*\\.vim$":     # Regex pattern for matching files
        conditions:                  # File-specific conditions
          os:
            - "linux"                # Only link color schemes on Linux
      "plugins/nerdtree.vim":        # Specific file path
        conditions:
          executable:                # Only link if NERDTree plugin requirements are met
            - "git"

  # Neovim configuration
  nvim:
    target_dir: "/home/username/.config/nvim"
    conditions:
      executable:
        - "nvim"
    file_overrides:
      "init.vim":
        force: true                  # Always overwrite init.vim without asking

  # Shell configurations
  shell:
    file_overrides:
      "bashrc":
        target_dir: "/home/username"  # Will create ~/.bashrc
        conditions:
          executable:
            - "bash"
      "zshrc":
        target_dir: "/home/username"  # Will create ~/.zshrc
        conditions:
          executable:
            - "zsh"
      "common_aliases":              # Shared between shells
        target_dir: "/home/username"  # Will create ~/.common_aliases

  # Git configuration with OS-specific settings
  git:
    file_overrides:
      "gitconfig.common":            # Common git config
        target_dir: "/home/username"
        force: true
      "gitconfig.linux":
        target_dir: "/home/username"
        conditions:
          os:
            - "linux"
      "gitconfig.darwin":
        target_dir: "/home/username"
        conditions:
          os:
            - "darwin"

  # Terminal multiplexer with version-specific configs
  tmux:
    conditions:
      executable:
        - "tmux"
    file_overrides:
      "tmux.conf.new":
        target_dir: "/home/username"
        targetName: ".tmux.conf"  # Symlink will be created as .tmux.conf
        conditions:
          executable_version:
            "tmux": ">=3.0"
      "tmux.conf.legacy":
        target_dir: "/home/username"
        targetName: ".tmux.conf"  # Symlink will be created as .tmux.conf
        conditions:
          executable_version:
            "tmux": "<3.0"
  waybar:
    file_overrides:
      "configc_hyprland.json":
        target_name: "configc.json" # Target name for the symlink
        conditions:
          executable: ["hyprland"] # Only link if Hyprland is installed
      "configc_sway.json":
        target_name: "configc.json"
        conditions:
          executable: ["sway"] # Only link if Sway is installed
      "start_waybar_sway.sh":
        target_name: "start_waybar.sh"
        conditions:
          executable: ["sway"]
      "regex:^.*hyprland.*": # Regex to match all other files with hyprland in the name
        conditions:
          executable: ["hyprland"]
      "regex:^.*sway.*": # Regex to match all other files with sway in the name
        conditions:
          executable: ["sway"]

  # Development tools
  dev:
    conditions:                      # Package-level conditions
      os:
        - "linux"
        - "darwin"
    file_overrides:
      "regex:^\\.?eslintrc(\\.json)?$":  # Match .eslintrc or eslintrc.json
        conditions:
          executable:
            - "node"
            - "npm"
          executable_version:
            "node": ">=12.0.0"
      "regex:^\\.?prettierrc(\\.json)?$":
        conditions:
          executable:
            - "node"
            - "npm"
      ".editorconfig":               # Editor configuration
        target_dir: "/home/username"  # Goes in home directory
        force: true                  # Always overwrite

  # Linux-specific configurations
  linux:
    conditions:
      os:
        - "linux"
    file_overrides:
      "i3/config":                   # i3 window manager config
        target_dir: "/home/username/.config/i3"
        conditions:
          executable:
            - "i3"
      "regex:^polybar/.*":           # All polybar configs
        target_dir: "/home/username/.config/polybar"
        conditions:
          executable:
            - "polybar"
      "picom.conf":
        target_dir: "/home/username/.config"
        conditions:
          executable:
            - "picom"

  # macOS-specific configurations
  macos:
    conditions:
      os:
        - "darwin"
    file_overrides:
      "DefaultKeyBinding.dict":
        target_dir: "/home/username/Library/KeyBindings"
      "regex:^karabiner/.*":
        target_dir: "/home/username/.config/karabiner"
        conditions:
          executable:
            - "karabiner_cli"

  # Distribution-specific configurations
  arch:
    conditions:
      distro:
        - "arch"
    file_overrides:
      "pacman.conf":
        target_dir: "/etc"
        backup_dir: "/home/username/.dloom/backups/etc"
        conditions:
          # Only link if user has sudo access to modify system files
          executable:
            - "sudo"

  ubuntu:
    conditions:
      distro:
        - "ubuntu"
        - "debian"
    file_overrides:
      "apt/preferences":
        target_dir: "/etc/apt"
        backup_dir: "/home/username/.dloom/backups/etc/apt"
        conditions:
          executable:
            - "sudo"
            - "apt"
