name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Set VERSION from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build the project
        run: |
          go build -ldflags "-X main.Version=${{ env.VERSION }}" -o build/dloom

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/dloom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}